Setup

In [157]:
import numpy as np
import time

Section 1 — ndarray Fundamentals

Task 1.1: Array Creation & Shapes

In [158]:
# TODO:
# Create a 1D array with values 0 to 99 (no loops)

# HINT:
# - Use np.arange

arr_1d = np.arange(100)
arr_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [159]:
# TODO:
# Reshape arr_1d into a (10, 10) array

# HINT:
# - reshape does NOT copy data

arr_2d = arr_1d.reshape(10,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [160]:
# TODO:
# Create a 3D array of shape (4, 5, 3)

# HINT:
# - Total elements must match

arr_3d = np.arange(60).reshape(4,5,3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

**Explain:**
- What does `.shape` represent?
- Why does contiguous memory matter?


Section 1.2 — dtype & Memory

In [161]:
# TODO:
# Create two arrays with same values but different dtypes

arr_int = np.arange(1000).astype(np.int64)
arr_float = np.arange(1000).astype(np.float64)
arr_int
arr_float

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

In [162]:
# TODO:
# Compare memory usage

# HINT:
# - Use .nbytes
print("arr_int size:",arr_int.nbytes)

print("arr_float size:",arr_float.nbytes)


arr_int size: 8000
arr_float size: 8000


**Interview Question:**  
Why does dtype selection matter in large ML pipelines?


Section 2 — Indexing, Views & Copies

Task 2.1: Views vs Copies

In [163]:
# TODO:
# Create a 2D array and slice every alternate row

# HINT:
# - Use slicing, not fancy indexing

A = np.arange(10).reshape(5,2)
A_slice = A[::2]
A
A_slice


array([[0, 1],
       [4, 5],
       [8, 9]])

In [164]:
# TODO:
# Modify A_slice and observe A
A_slice[0,0]=999
A


array([[999,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9]])

Explain:
- Why did the original array change (or not)?


Section 2.2 — Boolean Masking

In [165]:
# TODO:
# Create random array of size 1000
rng = np.random.default_rng(10)
X = rng.standard_normal(1000)
X

array([-1.10333845e+00, -7.25024640e-01, -7.81805257e-01,  2.66975856e-01,
       -2.48580729e-01,  1.26483052e-01,  8.43042571e-01,  8.57936549e-01,
        4.75183642e-01, -4.50768598e-01, -7.54932282e-01, -8.14814107e-01,
       -3.43854858e-01, -5.13800938e-02, -9.72273677e-01, -1.13448753e+00,
        3.05705219e-01, -1.85168503e+00, -1.77053508e-01,  4.25825667e-01,
       -9.85355606e-01, -1.11295413e+00, -7.60626032e-01,  6.48024589e-01,
       -1.29831356e-01, -1.86959723e+00, -4.23349110e-01,  1.01389680e+00,
        9.83715344e-01,  6.30041951e-01, -2.38058805e-01, -1.84493988e+00,
        1.69577729e-01, -1.75977764e-01,  7.67998645e-02,  1.54230411e+00,
        1.83683539e-01,  2.76333811e-01,  6.05097487e-01, -2.56568907e-01,
       -6.64356336e-01, -7.37373046e-01,  7.66966485e-01,  5.04552694e-01,
       -4.89546472e-01,  1.15269532e+00,  1.84331481e-01, -1.34021839e+00,
        6.05878965e-01, -1.39485678e-01, -1.32880182e+00,  5.15484846e-01,
       -3.44816518e-01, -

In [166]:
# TODO:
# Extract values greater than mean

# HINT:
# - Mean first
# - Boolean mask
mean = X.mean()
X_gt_mean = X[X > mean]

X_gt_mean


array([ 2.66975856e-01,  1.26483052e-01,  8.43042571e-01,  8.57936549e-01,
        4.75183642e-01, -5.13800938e-02,  3.05705219e-01,  4.25825667e-01,
        6.48024589e-01,  1.01389680e+00,  9.83715344e-01,  6.30041951e-01,
        1.69577729e-01,  7.67998645e-02,  1.54230411e+00,  1.83683539e-01,
        2.76333811e-01,  6.05097487e-01,  7.66966485e-01,  5.04552694e-01,
        1.15269532e+00,  1.84331481e-01,  6.05878965e-01,  5.15484846e-01,
        5.89895917e-01,  2.49163575e-01,  6.75019930e-01,  6.11742766e-01,
        8.04631587e-01,  5.70029200e-01, -6.75682448e-02,  3.25280051e-01,
        5.19413335e-01,  1.72106998e+00,  1.10660861e+00,  5.84012043e-01,
        1.51634126e-02,  8.14011591e-01,  1.28789102e-01,  3.86684259e-01,
        1.73476660e+00,  1.06500311e+00,  9.16564686e-01,  1.17142392e-01,
        9.94687152e-01,  9.35990425e-01,  2.64899548e-02,  2.07017858e+00,
        4.53437214e-01,  1.00842980e+00,  1.21160857e+00,  1.65205247e+00,
        1.62453073e+00,  

In [167]:
# TODO:
# Replace negative values with 0 (no loops)
X_copy = X.copy()
X_copy[X_copy<0] = 0

X_copy

print('mean',mean)
print('above mean count:',X_gt_mean.size)
print('negative after replacing:',(X_copy < 0).sum())

mean -0.06888960857515684
above mean count: 501
negative after replacing: 0


Section 3 — Broadcasting

Task 3.1: Broadcasting Rules

In [168]:
# TODO:
# Create A (1000, 50) and b (50,)
rng = np.random.default_rng(1)
A = rng.standard_normal((1000,50))
b = rng.standard_normal((50,))
b.shape

(50,)

In [169]:
# TODO:
# Add b to each row of A
A_plus = A + b
print("A",A)
print("b",b)
print("A_plus",A_plus)
A_plus.shape
# HINT:
# - No reshape required


A [[ 0.34558419  0.82161814  0.33043708 ... -0.50629166  0.59374807
   0.89116695]
 [ 0.3208483  -0.81823023  0.73165228 ...  0.0330001  -1.42534896
   0.33281361]
 [-0.65128101  0.8624448  -0.12559208 ...  0.42514874  0.28241584
  -1.15929673]
 ...
 [ 2.63806388  0.1786702  -1.503011   ... -0.89979321 -1.09720577
   2.45949873]
 [ 0.25460571 -0.64984191  0.02022446 ...  0.69710746 -1.57753933
  -0.47634927]
 [-0.4769489  -0.49410047 -0.81352119 ... -0.38350551 -0.34688599
  -0.18918713]]
b [-0.02215035  0.42352295  0.83961772  0.13917553  1.63394651 -0.76185535
 -0.46289533  0.32236092  0.12571245  0.47426305  0.05006911  0.70806523
  0.01446776 -1.68793899  0.21504247 -0.82351637  0.80367564  0.92058909
 -0.23200302 -2.04936228  1.60474282 -0.27090957  0.34082181 -1.19988925
 -0.66366466 -1.1153355   0.79699651  2.02121366 -1.37273641 -0.75996509
 -0.72778754 -1.65573038 -1.10682092  0.53172428 -0.23391387 -0.73098463
  1.81925951  1.76574199 -0.65318475  1.10633212 -0.20341185 -0.10

(1000, 50)

In [170]:
# TODO:
#one of the usecases of broadcasting is normalization
# Normalize each row of A
# Normalization = rescaling data so values are on a comparable scale.
# HINT:
# - Axis matters
# - Keep dimensions in mind
# there are different types of normalization, min max normalization and this is the standard normalization
# row - mean(row) / std(row)
row_mean = A.mean(axis=1,keepdims=True)
#keep dims make other column as 1 otherwise it would have been a 1D array with 1000 values
#for 1000 row we have the mean in single col
#row_mean.shape
#standard divation is square root of each value in the row - mean / total no of values (sq root of avg squared distance from mean)
row_std = A.std(axis=1,keepdims=True)
#row_std.shape
A_norm = (A-row_mean)/row_std
A_norm.shape

(1000, 50)

Explain broadcasting step-by-step.


Section 3.2 — Broadcasting Trap

In [171]:
# TODO:
# Intentionally trigger a broadcasting error
# Then fix it

col = np.arange(1000)
col.shape
try:
  _ = A - col
except ValueError as e:
  print('Expected broadcasting error:',e)
col2 = col.reshape(-1,1)
A_fixed = A - col2
print('Fixed shape after substraction:',A_fixed.shape)

Expected broadcasting error: operands could not be broadcast together with shapes (1000,50) (1000,) 
Fixed shape after substraction: (1000, 50)


What was wrong with the original shapes?


Section 4 — Vectorization vs Loops

Task 4.1: Loop vs Vectorized

In [186]:
# TODO:
# Create large array X of size 1,000,000
rng = np.random.default_rng(2)
X = rng.standard_normal(1_000_000)
X.shape

(1000000,)

In [187]:
# TODO:
# Normalize using Python loop

# HINT:
# - Time it
#mean of all 1 million values
mu = X.mean()
#std of all 1 million values
sigma = X.std()
t0 = time.time()
out_loop = np.empty_like(X)
for i in range(X.shape[0]):
  out_loop[i] = (X[i]-mu)/sigma
time_taken = time.time() - t0
print(round(time_taken,4))




0.8823


In [189]:
# TODO:
# Normalize using vectorization
t1= time.time()
out_vec = (X - mu)/sigma
vec_time = time.time() - t1
print(round((time_taken)/max(vec_time,1e-12),1))

61.8


:Why is vectorization faster?


Task 4.2: Pairwise Distance (FAANG Classic)

In [175]:
# TODO:
# Compute pairwise Euclidean distance matrix without loops

# HINT:
# - Use (x - y)^2 expansion
# - Broadcasting is key

def pairwise_distance(X):
    ...


Section 5 — Numerical Stability

Task 5.1: Softmax

In [176]:
# TODO:
# Implement naive softmax

def softmax_naive(X):
    ...


In [177]:
# TODO:
# Fix numerical instability

# HINT:
# - Subtract max per row

def softmax_stable(X):
    ...


Why does subtracting max work?


Section 6 — Linear Algebra

Task 6.1: Matrix Multiplication

In [178]:
# TODO:
# Try valid and invalid matrix multiplications



Explain difference between dot, @, and matmul.


Task 6.2: Solving Linear Systems

In [179]:
# TODO:
# Solve Ax = b and verify solution


Section 7 — Performance & Memory

Task 7.1: In-Place Operations

In [180]:
# TODO:
# Compare in-place vs out-of-place operations




Task 7.2: Strides

In [181]:
# TODO:
# Inspect array strides and explain



Section 8 — Mini Case Study

In [182]:
# TODO:
# Given X (10000, 100):
# - Normalize features
# - Compute covariance
# - Extract top-k eigenvectors



Explain each step and its ML relevance.


1. Where did NumPy save memory?
2. Where did it avoid Python overhead?
3. Which operation would break at scale?
